// tests/test_cortex_decide_golden_parity.ts — cross-language GOLDEN tripwire for the cortex
// decision-trace (seam Inc 4, task B-5).
//
// The fixture tests/fixtures/cortex_decide_golden.json is generated by actually running
// python dispatch.handle on each request (scripts-equivalent: the fixture was built live). This
// TS side validates that:
//   1. Each ok:true response parses cleanly through CortexDecideResponseSchema (shape drift → red).
//   2. The decision.keep, trace.strategy, and trace.shadowBudget presence all match the frozen values.
//   3. The ok:false vector has the correct error code shape.
//
// The Python side (python/synthesizer/tests/test_cortex.py::test_dispatch_golden_parity) is the
// real re-execution alarm: it re-runs dispatch.handle on each request and asserts the response
// equals the frozen golden. A cortex.py behaviour change → BOTH sides go red.
//
// Runner: npx tsx --test --test-force-exit tests/test_cortex_decide_golden_parity.ts
import { describe, it } from "node:test";
import assert from "node:assert";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { CortexDecideResponseSchema, type CortexDecideResponse } from "../src/memory/types";

const here = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.join(here, "fixtures", "cortex_decide_golden.json");

interface GoldenVector {
  name: string;
  request: Record<string, unknown>;
  response: Record<string, unknown>;
}

function loadVectors(): GoldenVector[] {
  const raw = JSON.parse(fs.readFileSync(FIXTURE, "utf-8"));
  assert.ok(Array.isArray(raw), "fixture must be a JSON array");
  return raw as GoldenVector[];
}

describe("cortex.decide golden-master parity (TS schema + shape lock)", () => {
  const vectors = loadVectors();

  it("fixture has >= 5 vectors", () => {
    assert.ok(vectors.length >= 5, `expected >= 5 vectors, got ${vectors.length}`);
  });

  it("all ok:true vectors parse cleanly through CortexDecideResponseSchema", () => {
    const okVectors = vectors.filter((v) => (v.response as { ok: boolean }).ok === true);
    assert.ok(okVectors.length >= 4, `expected >= 4 ok:true vectors, got ${okVectors.length}`);
    const failures: string[] = [];
    for (const v of okVectors) {
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success) {
        failures.push(`  [${v.name}]: ${JSON.stringify(result.error.issues)}`);
      }
    }
    assert.equal(
      failures.length,
      0,
      `${failures.length} ok:true vector(s) failed CortexDecideResponseSchema:\n${failures.join("\n")}`,
    );
  });

  it("ok:false vector has CORTEX_FAILED error code and parses through schema", () => {
    const failVec = vectors.find((v) => (v.response as { ok: boolean }).ok === false);
    assert.ok(failVec, "expected at least one ok:false vector in the fixture");
    const result = CortexDecideResponseSchema.safeParse(failVec!.response);
    assert.ok(result.success, `ok:false vector failed schema parse: ${JSON.stringify(!result.success ? result.error : null)}`);
    if (result.success) {
      const data: CortexDecideResponse = result.data;
      if (data.ok === false) {
        assert.equal(
          data.error.code,
          "CORTEX_FAILED",
          `expected CORTEX_FAILED, got ${data.error.code}`,
        );
      }
    }
  });

  it("frozen decision.keep values match for ok:true vectors", () => {
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as { ok: boolean; decision?: { keep: string[] } };
      if (!resp.ok) continue;
      const frozenKeep = resp.decision!.keep;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok) continue;
      const parsedKeep = result.data.decision.keep;
      if (JSON.stringify(parsedKeep) !== JSON.stringify(frozenKeep)) {
        mismatches.push(
          `  [${v.name}]: frozen=${JSON.stringify(frozenKeep)} parsed=${JSON.stringify(parsedKeep)}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `decision.keep mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("frozen trace.strategy values match for ok:true vectors", () => {
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as { ok: boolean; trace?: { strategy: string } };
      if (!resp.ok) continue;
      const frozenStrategy = resp.trace!.strategy;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok) continue;
      const parsedStrategy = result.data.trace.strategy;
      if (parsedStrategy !== frozenStrategy) {
        mismatches.push(
          `  [${v.name}]: frozen=${frozenStrategy} parsed=${parsedStrategy}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `trace.strategy mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("shadowBudget presence matches frozen values (present / absent) for ok:true vectors", () => {
    // Vector 'shadow-budget-absent' must have no shadowBudget; all others must have it.
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as { ok: boolean; trace?: { shadowBudget?: unknown } };
      if (!resp.ok) continue;
      const frozenHasBudget = resp.trace!.shadowBudget !== undefined;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok) continue;
      const parsedHasBudget = result.data.trace.shadowBudget !== undefined;
      if (parsedHasBudget !== frozenHasBudget) {
        mismatches.push(
          `  [${v.name}]: frozen shadowBudget present=${frozenHasBudget} parsed=${parsedHasBudget}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `shadowBudget presence mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("shadowBudget shape (perTierChars + textLen) matches frozen values where present", () => {
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as {
        ok: boolean;
        trace?: { shadowBudget?: { perTierChars: Record<string, number>; textLen: number } };
      };
      if (!resp.ok || !resp.trace?.shadowBudget) continue;
      const frozen = resp.trace.shadowBudget;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok || !result.data.trace.shadowBudget) continue;
      const parsed = result.data.trace.shadowBudget;
      if (
        JSON.stringify(parsed.perTierChars) !== JSON.stringify(frozen.perTierChars) ||
        parsed.textLen !== frozen.textLen
      ) {
        mismatches.push(
          `  [${v.name}]: frozen=${JSON.stringify(frozen)} parsed=${JSON.stringify(parsed)}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `shadowBudget shape mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("shadow-budget-absent vector has no shadowBudget in trace", () => {
    const v = vectors.find((x) => x.name === "shadow-budget-absent-command-outcome");
    assert.ok(v, "expected a vector named 'shadow-budget-absent-command-outcome' in the fixture");
    const resp = v!.response as { ok: boolean; trace?: { shadowBudget?: unknown } };
    assert.ok(resp.ok, "shadow-budget-absent vector must be ok:true");
    assert.equal(
      resp.trace?.shadowBudget,
      undefined,
      "shadow-budget-absent vector must NOT have shadowBudget in trace",
    );
  });

  it("shadowBudgetCurated presence matches frozen values (present only on drop) for ok:true vectors", () => {
    // The curated render (o23) is emitted ONLY when the cortex dropped a tier; presence must match frozen.
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as { ok: boolean; trace?: { shadowBudgetCurated?: unknown } };
      if (!resp.ok) continue;
      const frozenHas = resp.trace!.shadowBudgetCurated !== undefined;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok) continue;
      const parsedHas = result.data.trace.shadowBudgetCurated !== undefined;
      if (parsedHas !== frozenHas) {
        mismatches.push(
          `  [${v.name}]: frozen shadowBudgetCurated present=${frozenHas} parsed=${parsedHas}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `shadowBudgetCurated presence mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("shadowBudgetCurated shape (perTierChars + textLen) matches frozen values where present", () => {
    const mismatches: string[] = [];
    for (const v of vectors) {
      const resp = v.response as {
        ok: boolean;
        trace?: { shadowBudgetCurated?: { perTierChars: Record<string, number>; textLen: number } };
      };
      if (!resp.ok || !resp.trace?.shadowBudgetCurated) continue;
      const frozen = resp.trace.shadowBudgetCurated;
      const result = CortexDecideResponseSchema.safeParse(v.response);
      if (!result.success || !result.data.ok || !result.data.trace.shadowBudgetCurated) continue;
      const parsed = result.data.trace.shadowBudgetCurated;
      if (
        JSON.stringify(parsed.perTierChars) !== JSON.stringify(frozen.perTierChars) ||
        parsed.textLen !== frozen.textLen
      ) {
        mismatches.push(
          `  [${v.name}]: frozen=${JSON.stringify(frozen)} parsed=${JSON.stringify(parsed)}`,
        );
      }
    }
    assert.equal(
      mismatches.length,
      0,
      `shadowBudgetCurated shape mismatch in ${mismatches.length} vector(s):\n${mismatches.join("\n")}`,
    );
  });

  it("exited-pane vector: curated render drops the pane tier and saves chars vs full", () => {
    const v = vectors.find((x) => x.name === "exited-pane-drops-pane-tier");
    assert.ok(v, "expected a vector named 'exited-pane-drops-pane-tier' in the fixture");
    const resp = v!.response as {
      ok: boolean;
      trace?: {
        shadowBudget?: { perTierChars: Record<string, number>; textLen: number };
        shadowBudgetCurated?: { perTierChars: Record<string, number>; textLen: number };
      };
    };
    assert.ok(resp.ok, "exited-pane vector must be ok:true");
    const full = resp.trace?.shadowBudget;
    const curated = resp.trace?.shadowBudgetCurated;
    assert.ok(full && curated, "exited-pane vector must have BOTH shadowBudget and shadowBudgetCurated");
    assert.equal(
      Object.prototype.hasOwnProperty.call(curated!.perTierChars, "pane"),
      false,
      "curated render must exclude the dropped 'pane' tier",
    );
    assert.ok(
      curated!.textLen < full!.textLen,
      `curated textLen (${curated!.textLen}) must be < full textLen (${full!.textLen})`,
    );
  });
});
